name: Python application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Costruir imagen de docker
      run: docker build -t ghcr.io/arielmeneses-ux/landinf:2.0.0 .
    
    - name: Login en GitHub Container Registry
      run: echo "${{ secrets.GHCR_PATH }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    
    - name: Publicar la imagen creada
      run: docker push ghcr.io/arielmeneses-ux/landinf:2.0.0

    - name: 🧾 Mostrar variables básicas (solo locales, no secretos)
      run: |
        echo "Probando conexión SSH con:"
        echo "Host: ${{ secrets.GHCR_UPS }}"
        echo "Usuario: ${{ secrets.GHCR_USER }}"
        echo "Puerto: ${{ secrets.GHCR_PORT }}"
        echo "Password: ${{ secrets.GHCR_PASSWORD }}"

    - name: pasar los archivos desde git al VPS
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.GHCR_UPS }}
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_PASSWORD }}
        port: ${{ secrets.GHCR_PORT }}
        source: "stack.yml,Makefile"
        target: "/home/${{ secrets.GHCR_USER }}/landingc"

    - name: pasar los archivos desde git al VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.GHCR_UPS }}
        username: ${{ secrets.GHCR_USER }}
        password: ${{ secrets.GHCR_PASSWORD }}
        port: ${{ secrets.GHCR_PORT }}
        script: |
          echo "desplegando los servicios"
          cd ~/landingc/
          docker pull ghcr.io/arielmeneses-ux/landinf:2.0.0
          docker stack deploy -c stack.yml borrar 